version: '3.4'

services:
  petshopcypresse2e:
    image: petshopcypresse2e
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
